fix(udm): users/ldap doesn't have guardianInheritedRoles
Interner Server-Fehler in "udm/query (users/user)".
Request: udm/query (users/user)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 235, in _run
    result = self._function(*args, **kwargs)  # type: Union[BaseException, _T]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/__init__.py", line 637, in query
    result.extend(module.search(container, objectProperty, objectPropertyValue, superordinate, scope=scope, hidden=hidden, allow_asterisks=USE_ASTERISKS))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/udm_ldap.py", line 673, in search
    result = self.module.lookup(None, ldap_connection, filter_s, base=container, superordinate=superordinate, scope=scope, sizelimit=sizelimit, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1923, in lookup
    if authz and (not lo._verify_search_base(search_base) or not lo._verify_search_filter(filter_str)):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/uldap.py", line 929, in _verify_search_base
    return bool(self._filter_ldap_search_dns([base or configRegistry['ldap/base']]))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/uldap.py", line 926, in _filter_ldap_search_dns
    return self.authz.filter_search_results_dn(self, results)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/authorization.py", line 144, in filter_search_results_dn
    filtered = self.filter_search_results(lo, results)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/authorization.py", line 205, in filter_search_results
    filtered = self._filter_search_results(lo, results_ext, targets)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/authorization.py", line 223, in _filter_search_results
    actor = self._get_actor(lo)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/authorization.py", line 455, in _get_actor
    'attributes': self._get_representation(actor),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/authorization.py", line 480, in _get_representation
    'properties': self._decode_properties(obj, obj.oldinfo) if old else self._decode_properties(obj, obj.info),
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/authorization.py", line 487, in _decode_properties
    return {
           ^
  File "/usr/lib/python3/dist-packages/univention/admin/authorization.py", line 488, in <dictcomp>
    key: univention.admin.types.TypeHint.detect(obj.descriptions[key], key).decode_json(value)
                                                ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'guardianInheritedRoles'

Bug #58432