Issue univention/ucsschool#1348: fix circular import for udm hooks
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/admin/hook.py", line 67, in import_hook_files
    exec(fd.read(), sys.modules[__name__].__dict__)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 45, in <module>
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/__init__.py", line 36, in <module>
    from .computer import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/computer.py", line 54, in <module>
    from .base import MultipleObjectsError, RoleSupportMixin, UCSSchoolHelperAbstractClass
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/base.py", line 65, in <module>
    from .meta import UCSSchoolHelperMetaClass
  File "/usr/lib/python3/dist-packages/ucsschool/lib/models/meta.py", line 46, in <module>
    udm_modules.update()
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 150, in update
    for root in univention.admin.handlers.__path__:  # type: ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'univention.admin' has no attribute 'handlers' (most likely due to a circular import)
```